/* tslint:disable */
/* eslint-disable */
/**
 * MailSender API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterClientRequestDto
 */
export interface RegisterClientRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequestDto
     */
    appId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequestDto
     */
    appName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterClientRequestDto
     */
    pass?: string | null;
}

/**
 * Check if a given object implements the RegisterClientRequestDto interface.
 */
export function instanceOfRegisterClientRequestDto(value: object): value is RegisterClientRequestDto {
    return true;
}

export function RegisterClientRequestDtoFromJSON(json: any): RegisterClientRequestDto {
    return RegisterClientRequestDtoFromJSONTyped(json, false);
}

export function RegisterClientRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterClientRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'pass': json['pass'] == null ? undefined : json['pass'],
    };
}

export function RegisterClientRequestDtoToJSON(json: any): RegisterClientRequestDto {
    return RegisterClientRequestDtoToJSONTyped(json, false);
}

export function RegisterClientRequestDtoToJSONTyped(value?: RegisterClientRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        'appName': value['appName'],
        'pass': value['pass'],
    };
}

