/* tslint:disable */
/* eslint-disable */
/**
 * MailSender API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMailRequestDto
 */
export interface SendMailRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SendMailRequestDto
     */
    to?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailRequestDto
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMailRequestDto
     */
    body?: string | null;
}

/**
 * Check if a given object implements the SendMailRequestDto interface.
 */
export function instanceOfSendMailRequestDto(value: object): value is SendMailRequestDto {
    return true;
}

export function SendMailRequestDtoFromJSON(json: any): SendMailRequestDto {
    return SendMailRequestDtoFromJSONTyped(json, false);
}

export function SendMailRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function SendMailRequestDtoToJSON(json: any): SendMailRequestDto {
    return SendMailRequestDtoToJSONTyped(json, false);
}

export function SendMailRequestDtoToJSONTyped(value?: SendMailRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
    };
}

