/* tslint:disable */
/* eslint-disable */
/**
 * MailSender API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SendMailRequestDto,
    SendMailRequestDtoFromJSON,
    SendMailRequestDtoToJSON,
} from '../models/SendMailRequestDto';

export interface MailSendPostRequest {
    sendMailRequestDto?: SendMailRequestDto;
}

/**
 * 
 */
export class MailApi extends runtime.BaseAPI {

    /**
     * Creates request options for mailSendPost without sending the request
     */
    async mailSendPostRequestOpts(requestParameters: MailSendPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/mail/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendMailRequestDtoToJSON(requestParameters['sendMailRequestDto']),
        };
    }

    /**
     */
    async mailSendPostRaw(requestParameters: MailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mailSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async mailSendPost(requestParameters: MailSendPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mailSendPostRaw(requestParameters, initOverrides);
    }

}
