/* tslint:disable */
/* eslint-disable */
/**
 * MailSender API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the RegisterClientRequestDto interface.
 */
export function instanceOfRegisterClientRequestDto(value) {
    return true;
}
export function RegisterClientRequestDtoFromJSON(json) {
    return RegisterClientRequestDtoFromJSONTyped(json, false);
}
export function RegisterClientRequestDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'appId': json['appId'] == null ? undefined : json['appId'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'pass': json['pass'] == null ? undefined : json['pass'],
    };
}
export function RegisterClientRequestDtoToJSON(json) {
    return RegisterClientRequestDtoToJSONTyped(json, false);
}
export function RegisterClientRequestDtoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'appId': value['appId'],
        'appName': value['appName'],
        'pass': value['pass'],
    };
}
