/* tslint:disable */
/* eslint-disable */
/**
 * MailSender API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the SendMailRequestDto interface.
 */
export function instanceOfSendMailRequestDto(value) {
    return true;
}
export function SendMailRequestDtoFromJSON(json) {
    return SendMailRequestDtoFromJSONTyped(json, false);
}
export function SendMailRequestDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}
export function SendMailRequestDtoToJSON(json) {
    return SendMailRequestDtoToJSONTyped(json, false);
}
export function SendMailRequestDtoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
    };
}
